"""
VectorStore: the pgvector-backed persistence + similarity-search layer.

Boundary: "store chunks with their embeddings; given a query vector, return
the nearest ones." This is deliberately a thin wrapper — the actual SQL is
written out explicitly below rather than generated by an ORM query builder,
because understanding *what a vector similarity query actually does* is a
core learning goal of this project, not an implementation detail to hide.

KEY CONCEPT — distance operator:
pgvector's `<=>` operator computes COSINE DISTANCE between two vectors
(1 - cosine_similarity). Smaller = more similar; 0 = identical direction.
We use cosine distance (vs. L2/Euclidean `<->`) because it measures the
*angle* between vectors, which is what OpenAI's embedding model is trained to
make meaningful — magnitude differences between two embeddings aren't
semantically significant for this model family. `ORDER BY embedding <=> :q
LIMIT k` is exactly "top-K nearest neighbors."

IDEMPOTENCY: `replace_document_chunks` deletes any existing chunks for a
document_id before inserting the new set, inside one transaction. Re-ingesting
the same document therefore replaces rather than duplicates its chunks — this
is the mechanism behind the "idempotent ingestion" requirement, not something
handled elsewhere.
"""
from __future__ import annotations

from uuid import UUID

from sqlalchemy import text
from sqlalchemy.orm import Session

from app.ingestion.chunking import Chunk
from app.retrieval.base import VectorStore
from app.retrieval.types import RetrievedChunk


class PgVectorStore(VectorStore):
    """VectorStore implementation backed by Postgres + the pgvector extension."""

    def __init__(self, session: Session):
        self._session = session

    def replace_document_chunks(
        self,
        document_id: UUID,
        chunks: list[Chunk],
        embeddings: list[list[float]],
    ) -> int:
        if len(chunks) != len(embeddings):
            raise ValueError("chunks and embeddings must be the same length")

        self._session.execute(
            text("DELETE FROM chunks WHERE document_id = :doc_id"), {"doc_id": str(document_id)}
        )

        for chunk, embedding in zip(chunks, embeddings):
            self._session.execute(
                text(
                    """
                    INSERT INTO chunks
                        (document_id, chunk_index, content, page_number, section_title,
                         char_start, char_end, token_count, embedding)
                    VALUES
                        (:document_id, :chunk_index, :content, :page_number, :section_title,
                         :char_start, :char_end, :token_count, :embedding)
                    """
                ),
                {
                    "document_id": str(document_id),
                    "chunk_index": chunk.chunk_index,
                    "content": chunk.content,
                    "page_number": chunk.page_number,
                    "section_title": chunk.section_title,
                    "char_start": chunk.char_start,
                    "char_end": chunk.char_end,
                    "token_count": chunk.token_count,
                    "embedding": _to_pgvector_literal(embedding),
                },
            )
        return len(chunks)

    def similarity_search(
        self,
        query_embedding: list[float],
        top_k: int,
        document_id: UUID | None = None,
        doc_type: str | None = None,
    ) -> list[RetrievedChunk]:
        """
        Cosine-distance nearest-neighbor search, optionally filtered by document
        or document type.

        Both filters demonstrate that metadata filtering and vector search are
        the SAME query in pgvector — additional `WHERE` clauses combined with
        `ORDER BY ... <=> ...`, not a separate system that needs to be merged
        with search results afterward.
        """
        filter_clauses = []
        params: dict = {"query_embedding": _to_pgvector_literal(query_embedding), "top_k": top_k}
        if document_id:
            filter_clauses.append("AND c.document_id = :document_id")
            params["document_id"] = str(document_id)
        if doc_type:
            filter_clauses.append("AND d.doc_type = :doc_type")
            params["doc_type"] = doc_type

        rows = self._session.execute(
            text(
                f"""
                SELECT c.id, c.document_id, c.chunk_index, c.content, c.page_number,
                       c.section_title, c.embedding <=> :query_embedding AS distance,
                       d.title AS document_title, d.source_uri,
                       COALESCE((d.metadata->>'sensitive')::boolean, false) AS is_sensitive
                FROM chunks c
                JOIN documents d ON d.id = c.document_id
                WHERE 1=1 {' '.join(filter_clauses)}
                ORDER BY c.embedding <=> :query_embedding
                LIMIT :top_k
                """
            ),
            params,
        ).all()

        return [
            RetrievedChunk(
                id=row.id,
                document_id=row.document_id,
                chunk_index=row.chunk_index,
                content=row.content,
                page_number=row.page_number,
                section_title=row.section_title,
                distance=float(row.distance),
                document_title=row.document_title,
                source_uri=row.source_uri,
                is_sensitive=row.is_sensitive,
            )
            for row in rows
        ]


def _to_pgvector_literal(embedding: list[float]) -> str:
    """pgvector accepts vectors as a string literal like '[0.1,0.2,...]' over the wire."""
    return "[" + ",".join(repr(float(x)) for x in embedding) + "]"
